server:
  port: 8081
spring:
  application:
    name: controller
  cloud:
    consul:
      host: 121.183.228.40
      port: 8500
    stream:
      bindings:
        reportToMain-out-0:
          producer:
            exchange-type: direct
          destination: reportToMain
        messageFromMain-in-0:
          consumer:
            exchange-type: direct
          destination: commandToController
        reportFromWorker-in-0:
          consumer:
            exchange-type: direct
          destination: report
        sendToWorker-out-0:
          producer:
            exchange-type: direct
          destination: command
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/
      database: controller

logging:
  level:
    com:
      ccwlab:
        controller: DEBUG

jwt:
  secret: secret
